# Generated by Django 4.1.10 on 2023-07-28 18:37

import app.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image', models.ImageField(upload_to='app/images/')),
                ('alttext', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('identifier', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('images', djongo.models.fields.ArrayField(model_container=app.models.Image)),
            ],
        ),
    ]
